# Copyright (c) 2026, Arm Limited.
# SPDX-License-Identifier: MIT

import sys
import pytest
import shrinkwrap.shrinkwrap as cli


def test_version(monkeypatch, capsys):
    monkeypatch.setattr(sys, "argv", ["shrinkwrap", "--version"])

    with pytest.raises(SystemExit) as exc:
        cli.main()

    assert exc.value.code == 0

    captured = capsys.readouterr()
    assert captured.out.strip().startswith("shrinkwrap version")

def test_inspect_ns_edk2_base(monkeypatch, capsys):
    monkeypatch.setattr(
        sys,
        "argv",
        ["shrinkwrap", "inspect", "ns-edk2-base.yaml"],
    )

    cli.main()

    output = capsys.readouterr().out

    # basic config info
    assert "name:" in output
    assert "ns-edk2-base.yaml" in output
    assert "concrete:" in output
    assert "False" in output

    # run-time variables
    assert "run-time vars:" in output
    assert "DTB:" in output
    assert "ROOTFS:" in output
    assert "KERNEL:" in output
    assert "FIP:" in output
    assert "BL1:" in output
    assert "CMDLINE:" in output

    # components section
    assert "components:" in output
    assert "acpica:" in output
    assert "edk2:" in output
    assert "edk2-platforms:" in output

def _comment_lines(text: str) -> list[str]:
    return [line.rstrip() for line in text.splitlines() if line.lstrip().startswith("#")]

def test_build_overlay_dry_run_ns_edk2_top_level_comments(monkeypatch, capsys):
    monkeypatch.setattr(
        sys,
        "argv",
        [
            "shrinkwrap",
            "build",
            "--overlay=arch/v9.3.yaml",
            "--dry-run",
            "ns-edk2.yaml",
        ],
    )

    cli.main()

    out = capsys.readouterr().out
    comments = _comment_lines(out)

    expected = [
        "# SHRINKWRAP AUTOGENERATED SCRIPT.",
        "# Exit on error.",
        "# Remove old package.",
        "# Create directory structure.",
        "# Sync git repo for config=ns-edk2 component=acpica.",
        "# Sync git repo for config=ns-edk2 component=dt.",
        "# Sync git repo for config=ns-edk2 component=edk2-platforms.",
        "# Sync git repo for config=ns-edk2 component=edk2.",
        "# Sync git repo for config=ns-edk2 component=tfa.",
        "# Build for config=ns-edk2 component=acpica.",
        "# Build for config=ns-edk2 component=dt.",
        "# Copy artifacts for config=ns-edk2 component=acpica.",
        "# Copy artifacts for config=ns-edk2 component=dt.",
        "# Copy artifacts for config=ns-edk2 component=edk2-platforms.",
        "# Build for config=ns-edk2 component=edk2.",
        "# Copy artifacts for config=ns-edk2 component=edk2.",
        "# Build for config=ns-edk2 component=tfa.",
        "# Copy artifacts for config=ns-edk2 component=tfa.",
        "# Build for config=ns-edk2 component=armdbg-script.",
    ]

    filtered = [c for c in comments if c in expected]
    assert filtered == expected

def get_comment_lines(text: str):
    return [
        line.strip()
        for line in text.splitlines()
        if line.strip().startswith("#")
    ]


def test_run_dry_run_comments(monkeypatch, capsys):
    monkeypatch.setattr(
        sys,
        "argv",
        [
            "shrinkwrap",
            "build",
            "--overlay=arch/v9.3.yaml",
            "--dry-run",
            "ns-edk2.yaml",
        ],
    )

    cli.main()

    output = capsys.readouterr().out
    comments = get_comment_lines(output)

    expected = [
        "# SHRINKWRAP AUTOGENERATED SCRIPT.",
        "# Exit on error.",
        "# Function to update submodules without recursion",
        "# Remove old package.",
        "# Create directory structure.",
        "# Sync git repo for config=ns-edk2 component=acpica.",
        "# Sync git repo for config=ns-edk2 component=dt.",
        "# Sync git repo for config=ns-edk2 component=edk2-platforms.",
        "# Sync git repo for config=ns-edk2 component=edk2.",
        "# Sync git repo for config=ns-edk2 component=tfa.",
        "# Build for config=ns-edk2 component=acpica.",
        "# Build for config=ns-edk2 component=dt.",
        "# Copy artifacts for config=ns-edk2 component=dt.",
        "# Build for config=ns-edk2 component=edk2.",
        "# Build for config=ns-edk2 component=tfa.",
        "# Copy artifacts for config=ns-edk2 component=tfa.",
        "# Build for config=ns-edk2 component=armdbg-script.",
    ]

    for comment in expected:
        assert comment in comments

def test_process_merge_overlay_ns_edk2(monkeypatch, capsys):
    monkeypatch.setattr(
        sys,
        "argv",
        [
            "shrinkwrap",
            "process",
            "--action=merge",
            "--overlay=arch/v9.3.yaml",
            "ns-edk2.yaml",
        ],
    )


    cli.main()

    out = capsys.readouterr().out

    expected_fragments = [
        "%YAML",
        "name: ns-edk2",
        "fullname: ns-edk2.yaml",
        "concrete: true",
        "build:",
        "acpica:",
        "edk2:",
        "tfa:",
        "revision:",
        "run:",
        "name: FVP_Base_RevC-2xAEMvA",
        "rtvars:",
        "KERNEL:",
        "ROOTFS:",
        "BL1:",
        "FIP:",
        "DTB:",
        "CMDLINE:",
        "prerun:",
        "cp ${rtvar:KERNEL} $${SEMIHOSTDIR}/Image",
        "cp ${rtvar:DTB} $${SEMIHOSTDIR}/fdt.dtb",
        "Image dtb=fdt.dtb ${rtvar:CMDLINE}",
        "terminals:",
        "bp.terminal_1:",
        "friendly: edk2",
    ]

    for fragment in expected_fragments:
        assert fragment in out
