variables:
  KUBERNETES_CPU_REQUEST: 32
  KUBERNETES_MEMORY_REQUEST: 16Gi
  SMOKE_TEST:
    value: "true"
    options:
      - "true"
      - "false"
    description: "If true, runs a subset of tests to speed up pipeline execution time."
  INVALIDATE_TEST_ASSETS:
    value: "false"
    options:
      - "true"
      - "false"
    description: "If true, forces any cached test assets to be invalidated prior to repopulation."
  INVALIDATE_DOCKER_ASSETS:
    value: "false"
    options:
      - "true"
      - "false"
    description: "If true, forces any cached docker assets to be invalidated prior to repopulation."

workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: always

stages:
  - prep
  - build
  - test
  - deploy

prep-docker-assets:
  stage: prep
  image: shrinkwraptool/base-slim:latest
  tags:
    - amd64
  cache:
    key: docker-assets
    policy: pull-push
    paths:
      - docker/assets/
  script:
    - |
      if [ "$INVALIDATE_DOCKER_ASSETS" == "true" ]; then
        echo "Invalidating docker assets cache..."
        rm -rf docker/assets/*
      fi
      echo "Populating docker assets cache for x86_64..."
      ./docker/build.sh --version none --arch x86_64
      echo "Populating docker assets cache for aarch64..."
      ./docker/build.sh --version none --arch aarch64

build-docker-image:
  stage: build
  image:
    # amd64 pinned to workaround https://github.com/GoogleContainerTools/kaniko/issues/2452
    # With newer versions, issue is triggered when wgetting FVP from arm.com (see docker/build.sh).
    # arm64 works with tip but is broken in a different way when pinned to 1.9.1.
    name: gcr.io/kaniko-project/executor:${KANIKO_VERSION}
    entrypoint: [""]
  parallel:
    matrix:
      - TAG: amd64
        KANIKO_VERSION: v1.9.1-debug
      - TAG: arm64
        KANIKO_VERSION: debug
  tags:
    - ${TAG}
  cache:
    key: docker-assets
    policy: pull
    paths:
      - docker/assets/
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY_IMAGE}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - ./docker/build.sh --driver kaniko --registry ${CI_REGISTRY_IMAGE} --version ${CI_PIPELINE_IID}

build-docker-manifest:
  stage: build
  image: shrinkwraptool/base-slim:latest
  tags:
    - amd64
  needs:
    - build-docker-image
  script:
    - mkdir bin
    - export PATH=${PWD}/bin:${PATH}
    - curl -LsS https://github.com/estesp/manifest-tool/releases/download/v2.0.6/binaries-manifest-tool-2.0.6.tar.gz | tar -xz -C bin
    - ./docker/publish.sh --driver manifest-tool --user ${CI_REGISTRY_USER} --password ${CI_REGISTRY_PASSWORD} --registry ${CI_REGISTRY_IMAGE} --version ${CI_PIPELINE_IID}

build-documentation:
  stage: build
  image: registry.gitlab.arm.com/tooling/shrinkwrap/base-slim:${CI_PIPELINE_IID}
  tags:
    - amd64
  needs:
    - build-docker-manifest
  script:
    - export PATH=$PWD/shrinkwrap:$PATH
    - export SHRINKWRAP_BUILD=$PWD/shrinkwrap_workspace
    - export SHRINKWRAP_PACKAGE=$PWD/shrinkwrap_workspace/package
    - rm -rf ./documentation/userguide/configstore/*
    - ./documentation/_scripts/genconfigstore.py
    - |
      if ! git diff --quiet; then
        echo "Config store documentation not up-to-date; run genconfigstore.py and commit changes."
        exit 1
      fi
    - pip3 install requests unicode-slugify
    - |
      if [ ${CI_COMMIT_BRANCH} == ${CI_DEFAULT_BRANCH} ]; then
        ./documentation/_scripts/rtdbuild.py --domain https://readthedocs.com --token ${READTHEDOCS_TOKEN} --project ${READTHEDOCS_PROJECT} --branch latest --state active
      else
        ./documentation/_scripts/rtdbuild.py --domain https://readthedocs.com --token ${READTHEDOCS_TOKEN} --project ${READTHEDOCS_PROJECT} --branch main --state inactive
        ./documentation/_scripts/rtdbuild.py --domain https://readthedocs.com --token ${READTHEDOCS_TOKEN} --project ${READTHEDOCS_PROJECT} --branch ${CI_COMMIT_BRANCH} --state inactive
      fi

prep-test-assets:
  stage: prep
  image: shrinkwraptool/base-slim:latest
  tags:
    - amd64
  cache:
    key: test-assets
    policy: pull-push
    paths:
      - test/assets/
  script:
    - |
      if [ "$INVALIDATE_TEST_ASSETS" == "true" ]; then
        echo "Invalidating test assets cache..."
        rm -rf test/assets/*
      fi
      if [ ! -f ./test/assets/.cache_exists ]; then
        echo "Generating test assets..."
        ./test/genassets.sh -R null
        echo > ./test/assets/.cache_exists
      fi

test-self:
  stage: test
  image: registry.gitlab.arm.com/tooling/shrinkwrap/base-full:${CI_PIPELINE_IID}
  parallel:
    matrix:
      - TAG:
        - amd64
        - arm64
  tags:
    - ${TAG}
  cache:
    key: test-assets
    policy: pull
    paths:
      - test/assets/
  script:
    - |
      SMOKE=
      if [ "$SMOKE_TEST" == "true" ]; then
        SMOKE="--smoke-test"
      fi
    - export PATH=$PWD/shrinkwrap:$PATH
    - export SHRINKWRAP_BUILD=$PWD/shrinkwrap_workspace
    - export SHRINKWRAP_PACKAGE=$PWD/shrinkwrap_workspace/package
    - rm -rf selftest-${TAG}.xml selftest-${TAG}.log
    - ./test/test.py --runtime null ${SMOKE} --fvpjobs 4 --junit selftest-${TAG}.xml | tee selftest-${TAG}.log
  artifacts:
    name: selftest-${TAG}
    paths:
      - selftest-${TAG}.xml
      - selftest-${TAG}.log
    reports:
      junit: selftest-${TAG}.xml
    when: always

deploy-docker-image:
  stage: deploy
  image: shrinkwraptool/base-slim:latest
  tags:
    - amd64
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    # Grab the current shrinkwrap version.
    - export PATH=$PWD/shrinkwrap:$PATH
    - VERSION=$(shrinkwrap --version | cut -d' ' -f3)

    # Install regctl.
    - mkdir bin
    - export PATH=${PWD}/bin:${PATH}
    - curl -LsS https://github.com/regclient/regclient/releases/latest/download/regctl-linux-amd64 > bin/regctl
    - chmod 755 bin/regctl
    - regctl registry login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWORD} docker.io

    # Tag with current shrinkwrap version.
    - regctl image copy registry.gitlab.arm.com/tooling/shrinkwrap/base-slim-nofvp:${CI_PIPELINE_IID} docker.io/shrinkwraptool/base-slim-nofvp:${VERSION}
    - regctl image copy registry.gitlab.arm.com/tooling/shrinkwrap/base-slim:${CI_PIPELINE_IID} docker.io/shrinkwraptool/base-slim:${VERSION}
    - regctl image copy registry.gitlab.arm.com/tooling/shrinkwrap/base-full-nofvp:${CI_PIPELINE_IID} docker.io/shrinkwraptool/base-full-nofvp:${VERSION}
    - regctl image copy registry.gitlab.arm.com/tooling/shrinkwrap/base-full:${CI_PIPELINE_IID} docker.io/shrinkwraptool/base-full:${VERSION}

    # Tag as latest too.
    - regctl image copy registry.gitlab.arm.com/tooling/shrinkwrap/base-slim-nofvp:${CI_PIPELINE_IID} docker.io/shrinkwraptool/base-slim-nofvp:latest
    - regctl image copy registry.gitlab.arm.com/tooling/shrinkwrap/base-slim:${CI_PIPELINE_IID} docker.io/shrinkwraptool/base-slim:latest
    - regctl image copy registry.gitlab.arm.com/tooling/shrinkwrap/base-full-nofvp:${CI_PIPELINE_IID} docker.io/shrinkwraptool/base-full-nofvp:latest
    - regctl image copy registry.gitlab.arm.com/tooling/shrinkwrap/base-full:${CI_PIPELINE_IID} docker.io/shrinkwraptool/base-full:latest
