# Copyright (c) 2025, Arm Limited.
# SPDX-License-Identifier: MIT

%YAML 1.2
---
description: >-
  Overlay for TFTF to build debug configuration.

buildex:
  btvars:
    TFTF_BUILD:
      value: debug

