# Copyright (c) 2022, Arm Limited.
# SPDX-License-Identifier: MIT

%YAML 1.2
---
description: >-
  Best choice for: I have a linux-system.axf boot-wrapper and want to run it.

  Build to wrap a provided kernel with boot-wrapper EL3 FW into
  linux-system.axf. Provide the kernel image via the KERNEL btvar, and
  optionally override the kernel command line by providing the CMDLINE btvar.

  Then run the boot-wrapper (or pass a separately created one as the BOOTWRAPPER
  rtvar) in the FVP. A ROOTFS can be optionally provided. If present it is
  loaded into the virtio block device (/dev/vda).

concrete: true

layers:
  - FVP_Base_RevC-2xAEMvA-base.yaml
  - dt-base.yaml

build:
  bootwrapper:
    repo:
      remote: https://git.kernel.org/pub/scm/linux/kernel/git/mark/boot-wrapper-aarch64.git
      revision: master

    toolchain: aarch64-linux-gnu-

    prebuild:
      - autoreconf -i
      - ./configure --host=aarch64-linux-gnu --enable-gicv3 --with-dtb="${btvar:DTB}" --with-kernel-image="${btvar:KERNEL}" --with-cmdline="${btvar:CMDLINE}"

    build:
      - make -j${param:jobs}

    artifacts:
      BOOTWRAPPER: ${param:sourcedir}/linux-system.axf

buildex:
  btvars:
    DTB:
      type: path
      value: ${artifact:DTB}

    KERNEL:
      type: path
      value: null

    CMDLINE:
      type: string
      value: console=ttyAMA0 earlycon=pl011,0x1c090000 root=/dev/vda ip=dhcp

run:
  rtvars:
    BOOTWRAPPER:
      type: path
      value: ${artifact:BOOTWRAPPER}

    ROOTFS:
      type: path
      value: ''

  params:
    -C pctl.startup: '*.*.*.*'
    -C bp.secure_memory: 0
    -a cluster*.cpu*: ${rtvar:BOOTWRAPPER}
    -C bp.virtioblockdevice.image_path: ${rtvar:ROOTFS}
    -C bp.pl011_uart0.shutdown_tag: '"System halted"'

  terminals:
    bp.terminal_0:
      friendly: ''
      type: stdinout
      no_color: true
