# Copyright (c) 2022, Arm Limited.
# SPDX-License-Identifier: MIT

%YAML 1.2
---
description: >-
  EDK2 UEFI firmware implementation for the FVP.

  Builds acpica from source as part of the build process.

build:
  acpica:
    repo:
      remote: https://github.com/acpica/acpica.git
      revision: "20260408"

    build:
      - make -j${param:jobs}

    artifacts:
      ACPICA:
        path: ${param:sourcedir}/generate/unix/bin
        export: false

  edk2-platforms:
    repo:
      remote: https://github.com/tianocore/edk2-platforms.git
      revision: d672a812054e9d4fe5868a1ee65f438c10710535

    artifacts:
      # Share the source directory with EDK2
      EDK2_PLATFORMS:
        path: ${param:sourcedir}
        export: false

  edk2:
    repo:
      remote: https://github.com/tianocore/edk2.git
      revision: edk2-stable202608

    toolchain: aarch64-none-elf-

    stderrfilt: true

    prebuild:
      # Change working directory to reduce build artifacts in repo
      - export WORKSPACE=${param:builddir}
      - export CONF_PATH=${param:builddir}/Conf
      - export EDK_TOOLS_PATH=${param:sourcedir}/BaseTools
      - export GCC_AARCH64_PREFIX=$$CROSS_COMPILE
      - export PACKAGES_PATH=${param:sourcedir}:${artifact:EDK2_PLATFORMS}
      - export IASL_PREFIX=${artifact:ACPICA}/
      - export PYTHON_COMMAND=/usr/bin/python3

      # Pre-build steps: create configuration + compile tools
      - mkdir -p $$CONF_PATH
      - source ${param:sourcedir}/edksetup.sh --reconfig
      - make -j${param:jobs} -C $$EDK_TOOLS_PATH

    params:
      -a: AARCH64
      -t: GCC
      -b: ${btvar:EDK2_BUILD}
      -n: ${param:jobs}

    build:
      - build ${param:join_space}
          -p Platform/ARM/VExpressPkg/ArmVExpress-FVP-AArch64.dsc
          -D EDK2_OUT_DIR=${param:builddir}
          --pcd PcdShellDefaultDelay=0
          --pcd PcdUefiShellDefaultBootEnable=1

    artifacts:
      EDK2: ${param:builddir}/${btvar:EDK2_BUILD}_GCC/FV/FVP_AARCH64_EFI.fd

buildex:
  btvars:
    EDK2_BUILD:
      type: string
      options:
        - RELEASE
        - DEBUG
      value: RELEASE
