# Copyright (c) 2025, Arm Limited.
# SPDX-License-Identifier: MIT

%YAML 1.2
---
description: >-
  Rusted-Firmware-A. This configuration runs RF-A with the default
  features along with its normal-world and secure-world tests.

concrete: true

layers:
  - FVP_Base_RevC-2xAEMvA-base.yaml
  - arch/v9.1.yaml
  - rfa-base.yaml
  - tfa-base.yaml

build:
  tfa:
    params:
      SPD: spmd
      SPMD_SPM_AT_SEL2: 0
      FVP_TRUSTED_SRAM_SIZE: 512
      BL31: ${artifact:RFA_BL31}
      BL32: ${artifact:BL32}
      BL33: ${artifact:BL33}

    artifacts:
      BL31: ${artifact:RFA_BL31}
      BL31_ELF:
        path: ${artifact:RFA_OUT}/bl31.elf
        export: false

  rfa:
    build:
      - make -j${param:jobs} ${param:join_equal} STF_IMAGES_FLAGS="--bin bl32" ${artifact:BL32}
      - make -j${param:jobs} ${param:join_equal} STF_IMAGES_FLAGS="--bin bl33" ${artifact:BL33}

    artifacts:
      BL32: ${artifact:RFA_OUT}/bl32.bin
      BL33: ${artifact:RFA_OUT}/bl33.bin

run:
  rtvars:
    BL1:
      type: path
      value: ${artifact:BL1}

    FIP:
      type: path
      value: ${artifact:FIP}

  params:
    -C cluster0.cpu0.semihosting-cwd: target
    -C cluster1.cpu0.semihosting-cwd: target
    -C bp.secureflashloader.fname: ${rtvar:BL1}
    -C bp.flashloader0.fname: ${rtvar:FIP}
