# Copyright (c) 2024, Arm Limited.
# SPDX-License-Identifier: MIT

%YAML 1.2
---
description: >-
  Layer builds TF-A, TF-RMM, along with the required device tree, configured for
  RME with Armv9.2 architecture extension. This yaml file can be customized and
  used as base for building higher layers.

layers:
  - FVP_Base_RevC-2xAEMvA-rme.yaml
  - tfa-base.yaml
  - rmm-base.yaml
  - dt-base.yaml
  - arch/v9.2.yaml

build:
  tfa:
    params:
      ENABLE_FEAT_RME: 1
      ENABLE_RMM: 1
      RMM: ${artifact:RMM}
      FVP_HW_CONFIG: ${artifact:DTB}

run:
  terminals:
    bp.terminal_3:
      friendly: rmm

  params:
    # If BRBE is implemented and this is set to true, disable BRBE recording.
    # All registers will be functional, but no branches will be recorded.
    # This will improve model performance for workloads that enable BRBE,
    # but don't care about the information stored in it.
    -C cluster0.brbe_disable_recording: 1
    -C cluster1.brbe_disable_recording: 1
