# Copyright (c) 2022, Arm Limited.
# SPDX-License-Identifier: MIT

ARG BASE
FROM ${BASE}

# Install packages that the FVP relies upon.
RUN apt-get install --assume-yes --no-install-recommends --option=debug::pkgProblemResolver=yes \
		libdbus-1-3 \
		libpulse0

# Install FVP_Base_RevC-2xAEMvA. This is parameterized so the caller can easily
# update the version and architecture for different builds, or even omit it by
# providing the special name "none".
ARG FVP_PKG_NAME
ARG FVP_MODEL_DIR
COPY assets/${FVP_PKG_NAME} /tools/.
RUN cd /tools \
	&& if [ "${FVP_PKG_NAME}" != "none" ]; then \
	    tar xf ${FVP_PKG_NAME}; \
	fi \
	&& rm ${FVP_PKG_NAME} \
	&& cd -

ENV FVP_MODEL_DIR="/tools/${FVP_MODEL_DIR}"
ENV PATH="${FVP_MODEL_DIR}:${PATH}"
