# Copyright (c) 2022, Arm Limited.
# SPDX-License-Identifier: MIT

%YAML 1.2
---
description: >-
  Generates a very simple rootfs as an ext2/4 image. Higher layers can modify
  the buildroot config by adding commands to prebuild.

concrete: true

build:
  buildroot:
    repo:
      remote: https://github.com/buildroot/buildroot.git
      revision: 2024.05.2

    toolchain: aarch64-linux-gnu-

    stderrfilt: true

    prebuild:
      # Building with the Docker runtime on macOS will fail while configuring
      # host-tar unless this variable is set.
      - export FORCE_UNSAFE_CONFIGURE=1

      # Start from default config, but allow higher level layers to modify it.
      - make BR2_JLEVEL=${param:jobs} O=${param:builddir} BR2_DEFCONFIG=${param:configdir}/buildroot.config defconfig
      # Uncomment the below line if you want to regenerate the defconfig and
      # save it to ${param:configdir}/buildroot.config
      # - make BR2_JLEVEL=${param:jobs} O=${param:builddir} BR2_DEFCONFIG=${param:configdir}/buildroot.config savedefconfig

    build:
      # Fakeroot takes a while to start when the file descriptor limit is high.
      # Reduce it to significantly accelerate the build.
      # - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=920913
      # - https://github.com/moby/moby/issues/45436
      - saved_limit=$$(ulimit -S -n)
      - new_limit=4096
      - if [ "$$new_limit" -lt "$$saved_limit" ]; then
      -   ulimit -S -n "$$new_limit"
      - fi

      # Build.
      - make BR2_JLEVEL=${param:jobs} O=${param:builddir}

      # Restore the previous file limit
      - ulimit -S -n "$$saved_limit"

    artifacts:
      BUILDROOT: ${param:builddir}/images/rootfs.ext2
      # Some scripts including test.py in shrinkwrap might depend on the
      # rootfs.ext4 which is just symlink to rootfs.ext2, copy that too
      BUILDROOT_EXT4: ${param:builddir}/images/rootfs.ext4
