# Copyright (c) 2022, Arm Limited.
# SPDX-License-Identifier: MIT

%YAML 1.2
---
description: >-
  Builds on cca-3world.yaml, but adds support for running Hafnium along with
  some secure partitions in Secure World.

concrete: true

layers:
  - cca-3world.yaml
  - hafnium-base.yaml
  # Provides secure partitions that run under Hafnium for demonstration.
  - tftf-base.yaml

build:
  tfa:
    params:
      SPD: spmd
      SPMD_SPM_AT_SEL2: 1
      SP_LAYOUT_FILE: ${artifact:SP_LAYOUT}
      BL32: ${artifact:HAFNIUM}

run:
  terminals:
    bp.terminal_2:
      friendly: hafnium
