# Copyright (c) 2022, Arm Limited.
# SPDX-License-Identifier: MIT

%YAML 1.2
---
description: >-
  Brings together a software stack to demonstrate Arm CCA running on FVP in a
  three-world configuration. Includes TF-A in root world, RMM in realm world,
  and Linux in Normal world.

  In order to launch realm VMs, the user must bring their own rootfs that
  contains a realm-aware kvmtool and an RSI-aware guest kernel image.

concrete: true

layers:
  - ns-edk2.yaml
  - rmm-base.yaml
  - linux-base.yaml
  - kvmtool-base.yaml
  - arch/v9.2.yaml

build:
  tfa:
    params:
      ENABLE_RME: 1
      RMM: ${artifact:RMM}
      CTX_INCLUDE_EL2_REGS: 1
      FVP_HW_CONFIG: ${artifact:DTB}

      # SME is not supported concurrently with CCA yet.
      ENABLE_SME_FOR_NS: 0
      ENABLE_SME_FOR_SWD: 0
      ENABLE_FEAT_HCX: 0

      # MTE is not supported by RMM yet.
      CTX_INCLUDE_MTE_REGS: 0

  edk2:
    repo:
      edk2-platforms:
        # Contains change to carve out 64MB for RMM.
        revision: 310d31231d69c378ff85d253477d830913b77739

  linux:
    repo:
      remote: https://git.gitlab.arm.com/linux-arm/linux-cca.git
      revision: cca-full/rfc-v1

  kvmtool:
    repo:
      dtc:
        revision: v1.6.1
      kvmtool:
        remote: https://gitlab.arm.com/linux-arm/kvmtool-cca
        revision: cca/rfc-v1

  kvm-unit-tests:
    repo:
      remote: https://gitlab.arm.com/linux-arm/kvm-unit-tests-cca
      revision: cca/rfc-v1

    toolchain: aarch64-linux-gnu-

    params:
      --arch: arm64
      --cross-prefix: $${CROSS_COMPILE}
      --target: kvmtool

    build:
      - ./configure ${param:join_equal}
      - make -j${param:jobs}
      - tar -caf ${param:builddir}/kvm-unit-tests.tgz -C ${param:sourcedir} .

    clean:
      - make -j${param:jobs} clean

    artifacts:
      KVM_UNIT_TESTS: ${param:builddir}/kvm-unit-tests.tgz

  edk2-cca-guest:
    repo:
      edk2:
        remote: https://git.gitlab.arm.com/linux-arm/edk2-cca.git
        revision: 2595_arm_cca_0abet0_rfc_v1

    toolchain: aarch64-none-elf-

    stderrfilt: true

    prebuild:
      - export WORKSPACE=${param:sourcedir}
      - export GCC5_AARCH64_PREFIX=$$CROSS_COMPILE
      - export PACKAGES_PATH=$$WORKSPACE/edk2
      - export IASL_PREFIX=${artifact:ACPICA}/
      - export PYTHON_COMMAND=/usr/bin/python3

    params:
      -a: AARCH64
      -t: GCC5
      -p: edk2/ArmVirtPkg/ArmVirtKvmTool.dsc
      -b: RELEASE

    build:
      - source edk2/edksetup.sh --reconfig
      - make -j${param:jobs} -C edk2/BaseTools
      - build -n ${param:jobs} -D EDK2_OUT_DIR=${param:builddir} ${param:join_space}

    artifacts:
      EDK2_CCA_GUEST: ${param:builddir}/RELEASE_GCC5/FV/KVMTOOL_EFI.fd

run:
  rtvars:
    KERNEL:
      value: ${artifact:KERNEL}

    CMDLINE:
      # Current RMM version (0.2.0) can only handle first bank of DRAM. This
      # should be fixed in the next release. But for now, limit the amount of
      # DRAM Linux sees so that it only delegates DRAM in the first bank.
      value: mem=1G console=ttyAMA0 earlycon=pl011,0x1c090000 root=/dev/vda ip=dhcp

  params:
    -C cluster0.rme_support_level: 2
    -C cluster1.rme_support_level: 2

    # SME is not supported concurrently with CCA yet.
    -C SVE.ScalableVectorExtension.has_sme: 0

    # MTE is not supported by RMM yet.
    -C cluster0.memory_tagging_support_level: 0
    -C cluster1.memory_tagging_support_level: 0

    # CCA-specific SMMU settings.
    -C pci.pci_smmuv3.mmu.SMMU_ROOT_IDR0: 3
    -C pci.pci_smmuv3.mmu.SMMU_ROOT_IIDR: 0x43B
    -C pci.pci_smmuv3.mmu.root_register_page_offset: 0x20000

  terminals:
    bp.terminal_3:
      friendly: rmm
