# Copyright (c) 2022, Arm Limited.
# SPDX-License-Identifier: MIT

%YAML 1.2
---
description: >-
  Brings together a software stack to demonstrate Arm CCA running on FVP in a
  four-world configuration. Includes TF-A in root world, Hafnium and some demo
  secure partitions in secure world, RMM in realm world, and Linux in Normal
  world.

  In order to launch realm VMs, the user must bring their own rootfs that
  contains a realm-aware kvmtool and an RSI-aware guest kernel image.

concrete: true

layers:
  - cca-3world.yaml
  - hafnium-base.yaml
  # Provides secure partitions that run under Hafnium for demonstration.
  - tftf-base.yaml

build:
  tfa:
    params:
      SPD: spmd
      SPMD_SPM_AT_SEL2: 1
      SP_LAYOUT_FILE: ${artifact:SP_LAYOUT}
      BL32: ${artifact:HAFNIUM}

run:
  terminals:
    bp.terminal_2:
      friendly: hafnium
