# Copyright (c) 2022, Arm Limited.
# SPDX-License-Identifier: MIT

%YAML 1.2
---
description: >-
  Builds a device tree from upstream linux kernel and exports the dtb as an
  artifact called DTB. By default, fvp-base-revc.dts is built, but the user can
  override this by specifying its name in the DTS variable as part of a higher
  layer's prebuild commands. Optionally, a kernel command line is dynamically
  added to the chosen node if any params are specified. Uses a slimmed down
  mirror of the upstream repo to avoid having to sync all of linux.

build:
  dt:
    repo:
      remote: https://git.kernel.org/pub/scm/linux/kernel/git/devicetree/devicetree-rebasing.git
      revision: v6.6-dts

    toolchain: aarch64-none-elf-

    prebuild:
      # User can override DTS in prebuild step of higher layer.
      - DTS=fvp-base-revc.dts
      # User can override these to define an initrd in memory.
      - INITRD_START=
      - INITRD_END=

    build:
      - DT_BASENAME=$$(basename $${DTS} .dts)
      - DTB_INTER=src/arm64/arm/$${DT_BASENAME}.dtb
      - DTB_FINAL=${param:builddir}/dt_bootargs.dtb

      # This script compiles the selected dts then dynamically adds kernel
      # bootargs to the chosen node. It uses any defined key=value pairs from
      # the `params` key. If none are defined (the default) the dts is compiled
      # without a command line. If an initrd location is provided, it is also
      # added to the chosen node.
      - make CPP=$${CROSS_COMPILE}cpp -j${param:jobs} $${DTB_INTER}
      - CHOSEN=
      - if [ ! -z "${param:join_equal}" ]; then
      -   CHOSEN="$${CHOSEN}bootargs = \"${param:join_equal}\";\n"
      - fi
      - if [ ! -z "$${INITRD_START}" ] && [ ! -z "$${INITRD_END}" ]; then
      -   INITRD_START_HI=$$((($${INITRD_START} >> 32) & 0xffffffff))
      -   INITRD_START_LO=$$(($${INITRD_START} & 0xffffffff))
      -   INITRD_END_HI=$$((($${INITRD_END} >> 32) & 0xffffffff))
      -   INITRD_END_LO=$$(($${INITRD_END} & 0xffffffff))
      -   CHOSEN="$${CHOSEN}linux,initrd-start = <$${INITRD_START_HI} $${INITRD_START_LO}>;\n"
      -   CHOSEN="$${CHOSEN}linux,initrd-end = <$${INITRD_END_HI} $${INITRD_END_LO}>;\n"
      - fi
      - if [ -z "$${CHOSEN}" ]; then
      -   cp $${DTB_INTER} $${DTB_FINAL}
      - else
      -   ( dtc -q -O dts -I dtb $${DTB_INTER} ; echo -e "/ { chosen { $${CHOSEN} }; };" ) | dtc -q -O dtb -o $${DTB_FINAL}
      - fi

      # When using the default fvp-base-revc.dts, an overlay is added which adds
      # extra properties that TFA requires. This allows embedding this DT
      # directly in the FIP rather than having TFA use its own DT then inject
      # this at a higher level. It's also not always possible to inject the DT
      # at a higher level anyway, due to TFA constraints. Included in the
      # overlay: a 64MB carve-out is reserved at the end of the first memory
      # bank, which is used by tfa and (if present) the rmm, timer frequency,
      # some extra psci properties, and cpu-map to map the cores to clusters.
      # By default the virtio-rng is disabled (because it was not present in
      # older builds of the rev C FVP), so enable it here, so Linux can use it
      # to initialize its RNG and speed up boot.
      - if [ "$${DTS}" = "fvp-base-revc.dts" ]; then
      - >-
          OVERLAY="/ {
            reserved-memory {
              fw: fw@7C000000 {
                reg = <0x00000000 0xFC000000 0 0x04000000>;
                no-map;
              };
            };
            timer {
              clock-frequency = <100000000>;
            };
            psci {
              compatible = \"arm,psci-1.0\", \"arm,psci-0.2\";
              max-pwr-lvl = <2>;
            };
            cpus {
              cpu-map {
                cluster0 {
                  core0 { cpu = <&{/cpus/cpu@0}>; };
                  core1 { cpu = <&{/cpus/cpu@100}>; };
                  core2 { cpu = <&{/cpus/cpu@200}>; };
                  core3 { cpu = <&{/cpus/cpu@300}>; };
                };
                cluster1 {
                  core0 { cpu = <&{/cpus/cpu@10000}>; };
                  core1 { cpu = <&{/cpus/cpu@10100}>; };
                  core2 { cpu = <&{/cpus/cpu@10200}>; };
                  core3 { cpu = <&{/cpus/cpu@10300}>; };
                };
              };
            };
            bus@8000000 {
              motherboard-bus@8000000 {
                iofpga-bus@300000000 {
                  virtio@200000 {
                    status = \"okay\";
                  };
                };
              };
            };
          };"
      -   ( dtc -q -O dts -I dtb $${DTB_FINAL} ; echo -e "$${OVERLAY}" ) | dtc -q -O dtb -o $${DTB_FINAL}
      - fi

    artifacts:
      DTB: ${param:builddir}/dt_bootargs.dtb
