# Copyright (c) 2022, Arm Limited.
# SPDX-License-Identifier: MIT

%YAML 1.2
---
description: >-
  EDK2 UEFI firmware implementation for the FVP.

  Builds acpica from source as part of the build process.

build:
  acpica:
    repo:
      remote: https://github.com/acpica/acpica.git
      revision: R09_27_24

    build:
      - rm -rf ${param:sourcedir}/generate/unix/acpica
      - make -j${param:jobs}
      - mv ${param:sourcedir}/generate/unix/bin ${param:sourcedir}/generate/unix/acpica

    artifacts:
      ACPICA: ${param:sourcedir}/generate/unix/acpica

  edk2:
    repo:
      edk2:
        remote: https://github.com/tianocore/edk2.git
        revision: 95d8a1c255cfb8e063d679930d08ca6426eb5701
      edk2-platforms:
        remote: https://github.com/tianocore/edk2-platforms.git
        revision: 5b5885ef3e30a2896f23afd6df3d2dae8d5e51b3

    toolchain: aarch64-none-elf-

    stderrfilt: true

    prebuild:
      - export WORKSPACE=${param:sourcedir}
      - export GCC5_AARCH64_PREFIX=$$CROSS_COMPILE
      - export PACKAGES_PATH=$$WORKSPACE/edk2:$$WORKSPACE/edk2-platforms
      - export IASL_PREFIX=${artifact:ACPICA}/
      - export PYTHON_COMMAND=/usr/bin/python3

    params:
      -a: AARCH64
      -t: GCC5
      -p: Platform/ARM/VExpressPkg/ArmVExpress-FVP-AArch64.dsc
      -b: DEBUG
      --pcd: PcdShellDefaultDelay=0
      ' --pcd': PcdUefiShellDefaultBootEnable=1

    build:
      - source edk2/edksetup.sh --reconfig
      - make -j${param:jobs} -C edk2/BaseTools
      - build -n ${param:jobs} -D EDK2_OUT_DIR=${param:builddir} ${param:join_space}

    artifacts:
      EDK2: ${param:builddir}/DEBUG_GCC5/FV/FVP_AARCH64_EFI.fd
