# Copyright (c) 2022, Arm Limited.
# SPDX-License-Identifier: MIT

%YAML 1.2
---
description: >-
  EDK2 UEFI firmware implementation for the FVP.

  Builds acpica from source as part of the build process.

build:
  acpica:
    repo:
      remote: https://github.com/acpica/acpica.git
      revision: R2025_04_04

    build:
      - make -j${param:jobs}

    artifacts:
      ACPICA:
        path: ${param:sourcedir}/generate/unix/bin
        export: false

  edk2:
    repo:
      edk2:
        remote: https://github.com/tianocore/edk2.git
        revision: edk2-stable202508.01
      edk2-platforms:
        remote: https://github.com/tianocore/edk2-platforms.git
        revision: 8cc9da9dc8431d1f0dfab28d92b3941e2c19aeb8

    toolchain: aarch64-none-elf-

    stderrfilt: true

    prebuild:
      - export WORKSPACE=${param:sourcedir}
      - export GCC_AARCH64_PREFIX=$$CROSS_COMPILE
      - export PACKAGES_PATH=$$WORKSPACE/edk2:$$WORKSPACE/edk2-platforms
      - export IASL_PREFIX=${artifact:ACPICA}/
      - export PYTHON_COMMAND=/usr/bin/python3

    params:
      -a: AARCH64
      -t: GCC
      -p: Platform/ARM/VExpressPkg/ArmVExpress-FVP-AArch64.dsc
      -b: ${btvar:EDK2_BUILD}
      --pcd: PcdShellDefaultDelay=0
      ' --pcd': PcdUefiShellDefaultBootEnable=1

    build:
      - source edk2/edksetup.sh --reconfig
      - make -j${param:jobs} -C edk2/BaseTools
      - build -n ${param:jobs} -D EDK2_OUT_DIR=${param:builddir} ${param:join_space}

    artifacts:
      EDK2: ${param:builddir}/${btvar:EDK2_BUILD}_GCC/FV/FVP_AARCH64_EFI.fd

buildex:
  btvars:
    EDK2_BUILD:
      type: string
      options:
        - RELEASE
        - DEBUG
      value: RELEASE
