# Copyright (c) 2024, Arm Limited.
# SPDX-License-Identifier: MIT

%YAML 1.2
---

layers:
  - FVP_Base_RevC-2xAEMvA-base.yaml
  - arch/v9.2.yaml

run:
  params:
    -C cluster0.rme_support_level: 2
    -C cluster1.rme_support_level: 2
    -C bp.secure_memory: 0                                         # Disable security checking by TZC-400
    -C bp.has_rme: 1                                               # Enable Realm Management Extension(RME) support
                                                                   # Only Root access to Trusted ROM and SRAM.
                                                                   # SECURE/ROOT access only for below peripherals:
                                                                   # -Trusted DRAM
                                                                   # -REFCLK CNTControl (Generic Timer)
                                                                   # -Trusted Watchdog SP805, Trustzone address space controller
                                                                   # -AP_REFCLK CNTBase0 (Generic Timer)
                                                                   # -Trusted RNG, Non-Volatile Counter and Root-Key Storage
                                                                   # -Flash0, Flash1
                                                                   # -uart0, uart1, uart2, uart3

    # Suppress "WARNING: MPAM_NS is deprecated when RME is in use. Should use MPAM_SP"
    -C cluster0.output_attributes: ExtendedID[62:55]=MPAM_PMG,ExtendedID[54:39]=MPAM_PARTID,ExtendedID[38:37]=MPAM_SP
    -C cluster1.output_attributes: ExtendedID[62:55]=MPAM_PMG,ExtendedID[54:39]=MPAM_PARTID,ExtendedID[38:37]=MPAM_SP

    # CCA-specific SMMU settings.
    -C pci.pci_smmuv3.mmu.SMMU_ROOT_IDR0: 3
    -C pci.pci_smmuv3.mmu.SMMU_ROOT_IIDR: 0x43B
    -C pci.pci_smmuv3.mmu.root_register_page_offset: 0x20000

    # FEAT_CSV2_2 is optional from Armv8.0. Enable this hw mitigation against
    # prediction resources side-channel speculation attacks, as it is reasonable
    # to assume Arm CCA systems implement it. TF-A detects the feature through
    # ID registers and permits its use by lower EL.
    -C cluster0.restriction_on_speculative_execution: 2
    -C cluster1.restriction_on_speculative_execution: 2
    -C cluster0.restriction_on_speculative_execution_aarch32: 2
    -C cluster1.restriction_on_speculative_execution_aarch32: 2

