# Copyright (c) 2022, Arm Limited.
# SPDX-License-Identifier: MIT

%YAML 1.2
---
description: >-
  kvmtool is a lightweight Virtual Machine Monitor that can be used, in concert
  with KVM, to create and manage virtual machines. This config fragment can be
  used to build the kvmtool binary, which is exported as an artifact called
  LKVM. Fancy optional extras which depend on 3rd party libraries are not
  enabled.

build:
  kvmtool:
    repo:
      dtc:
        remote: https://git.kernel.org/pub/scm/utils/dtc/dtc.git
        revision: v1.7.2
      kvmtool:
        remote: https://git.kernel.org/pub/scm/linux/kernel/git/will/kvmtool.git
        revision: 7ad32e5514aca2b6d19398fd3ae5a7c5e0e1ce24

    toolchain: aarch64-linux-gnu-

    build:
      - export CC=$${CROSS_COMPILE}gcc
      - export ARCH=arm64
      - export LIBFDT_DIR=${param:sourcedir}/dtc/libfdt
      - make -j${param:jobs} -C dtc libfdt
      - make -j${param:jobs} -C kvmtool

    artifacts:
      LKVM: ${param:sourcedir}/kvmtool/lkvm