# Copyright (c) 2025, Arm Limited.
# SPDX-License-Identifier: MIT

%YAML 1.2
---
description: >-
  Rusted-Firmware-A. This provides a baseline configuration that can be
  customized by higher layers.

layers:
  - rust.yaml

build:
  rfa:
    params:
      PLAT: fvp
      DEBUG: 0
      OBJCOPY: aarch64-none-elf-objcopy
      CARGO_TARGET_DIR: ${param:builddir}/target

    repo:
      remote: https://git.trustedfirmware.org/RF-A/rusted-firmware-a
      revision: v0.2.0

    prebuild:
      # Calling rustup to install the toolchain / components described
      # by `rust-toolchain.toml`
      - source ${artifact:RUST_ENV}
      - rustup show

    build:
      - source ${artifact:RUST_ENV}
      - make -j${param:jobs} ${param:join_equal} build

    artifacts:
      RFA_BL31: ${param:builddir}/target/bl31.bin
