# Copyright (c) 2022, Arm Limited.
# SPDX-License-Identifier: MIT

%YAML 1.2
---
build:
  rmm:
    repo:
      remote: https://git.trustedfirmware.org/TF-RMM/tf-rmm.git
      revision: tf-rmm-v0.9.0

    toolchain: aarch64-none-elf-

    params:
      -DRMM_CONFIG: fvp_defcfg
      -DCMAKE_BUILD_TYPE: ${btvar:RMM_BUILD}
      -DLOG_LEVEL: ${btvar:RMM_LOG_LEVEL}

    build:
      - cmake ${param:join_equal} -S . -B ${param:builddir}
      - cmake --build ${param:builddir} -j ${param:jobs}

    artifacts:
      RMM_OUT:
        path: ${param:builddir}/${btvar:RMM_BUILD}
        export: false
      RMM: ${artifact:RMM_OUT}/rmm.img

  armdbg-script:
    build:
      # parse load offset from app bundle info
      - RMM_OFFSET_FILE=${artifact:RMM_OUT}/bundle_app_out.txt
      - if test -f "$$RMM_OFFSET_FILE"; then
      -   RMM_LOAD_OFFSET=$$( cat $$RMM_OFFSET_FILE | sed -En
            's/.*RMM core is [0-9]+ \((0x[0-9A-Fa-f]+)\) bytes from.*/+\1/p' )
      - fi
      - ARMDBG_SCRIPT+="add-symbol-file ${artifact:RMM_OUT}/rmm.elf
                        EL2RL:${btvar:RMM_BASE}$${RMM_LOAD_OFFSET}"$$'\n'

buildex:
  btvars:
    RMM_BUILD:
      type: string
      options:
        - Release
        - Debug
      value: Release
    RMM_BASE:
      type: string
      value: '0xFDC00000'
    RMM_LOG_LEVEL:
      type: string
      value: 40
