# Copyright (c) 2022, Arm Limited.
# SPDX-License-Identifier: MIT

%YAML 1.2
---
build:
  rmm:
    repo:
      remote: https://git.trustedfirmware.org/TF-RMM/tf-rmm.git
      revision: tf-rmm-v0.8.0

    toolchain: aarch64-none-elf-

    params:
      -DRMM_CONFIG: fvp_defcfg
      -DCMAKE_BUILD_TYPE: ${btvar:RMM_BUILD}
      -DLOG_LEVEL: ${btvar:RMM_LOG_LEVEL}

    build:
      - cmake ${param:join_equal} -S . -B ${param:builddir}
      - cmake --build ${param:builddir} -j ${param:jobs}

    artifacts:
      RMM_OUT:
        path: ${param:builddir}/${btvar:RMM_BUILD}
        export: false
      RMM: ${artifact:RMM_OUT}/rmm.img

buildex:
  btvars:
    RMM_BUILD:
      type: string
      options:
        - Release
        - Debug
      value: Release
    RMM_LOG_LEVEL:
      type: string
      value: 40
