# Copyright (c) 2022, Arm Limited.
# SPDX-License-Identifier: MIT

%YAML 1.2
---
description: >-
  Trusted Firmware for A-class CPUs. This provides a baseline configuration that
  can be customized by higher layers.

build:
  tfa:
    repo:
      remote: https://git.trustedfirmware.org/TF-A/trusted-firmware-a.git
      revision: v2.13.0

    toolchain: aarch64-none-elf-

    params:
      PLAT: fvp
      DEBUG: 0
      LOG_LEVEL: 40
      ARM_DISABLE_TRUSTED_WDOG: 1
      FVP_HW_CONFIG_DTS: fdts/fvp-base-gicv3-psci-1t.dts

    prebuild:
      # tfa does not notice when parameters are changed and can therefore end up
      # with stale compilation units. Let's work around that by saving the
      # parameters and comparing to the last run. If they have changed, force a
      # clean. Also works for the case where shrinkwrap.params doesn't exist.
      - 'echo "${param:join_equal}" > ${param:builddir}/shrinkwrap.params.new'
      - if ! cmp -s "${param:builddir}/shrinkwrap.params.new" "${param:builddir}/shrinkwrap.params"; then
      -     make BUILD_BASE=${param:builddir} clean
      - fi
      - mv ${param:builddir}/shrinkwrap.params.new ${param:builddir}/shrinkwrap.params

    build:
      # tfa has makefile dependency bug that makes parallel make for more than
      # ~8 jobs unreliable, so limit it to 8.
      - "make BUILD_BASE=${param:builddir} ${param:join_equal} -j$$(( ${param:jobs} < 8 ? ${param:jobs} : 8 )) all fip"

    artifacts:
      BL1: ${param:builddir}/fvp/release/bl1.bin
      BL2: ${param:builddir}/fvp/release/bl2.bin
      BL31: ${param:builddir}/fvp/release/bl31.bin
      FIP: ${param:builddir}/fvp/release/fip.bin
