# Copyright (c) 2023, Arm Limited.
# SPDX-License-Identifier: MIT

%YAML 1.2
---
description: >-
  The Trusted Firmware-A Tests (TF-A-Tests) is a suite of baremetal tests that
  exercise the Trusted Firmware-A (TF-A) features. This provides a baseline
  configuration that can be customized by higher layers.

build:
  tftf:
    repo:
      remote: https://git.trustedfirmware.org/TF-A/tf-a-tests.git
      revision: v2.14.0

    toolchain: aarch64-none-elf-

    params:
      PLAT: fvp
      DEBUG: $$( test '${btvar:TFTF_BUILD}' != debug ; echo $$? )
      BUILD_BASE: ${param:builddir}
      LOG_LEVEL: ${btvar:TFTF_LOG_LEVEL}
      TESTS: ${btvar:TFTF_SUITE}
      ENABLE_REALM_PAYLOAD_TESTS: 1

    prebuild:
      # Taken from tfa-base.yaml as TF-A-Tests suffers from the same problem.
      - 'echo "${param:join_equal}" > ${param:builddir}/shrinkwrap.params.new'
      - if ! cmp -s "${param:builddir}/shrinkwrap.params.new" "${artifact:TFTF_OUT}/shrinkwrap.params"; then
      -     make ${param:join_equal} clean
      - fi
      - mkdir -p ${artifact:TFTF_OUT}
      - mv ${param:builddir}/shrinkwrap.params.new ${artifact:TFTF_OUT}/shrinkwrap.params

    build:
      # tfa-tests has makefile dependency bug that makes parallel make for more
      # than ~8 jobs unreliable, so limit it to 8.
      - "make ${param:join_equal} -j$$(( ${param:jobs} < 8 ? ${param:jobs} : 8 )) all"

    artifacts:
      TFTF_OUT:
        path: ${param:builddir}/fvp/${btvar:TFTF_BUILD}
        export: false
      TFTF_BIN: ${artifact:TFTF_OUT}/tftf.bin
      SP_LAYOUT: ${artifact:TFTF_OUT}/sp_layout.json

buildex:
  btvars:
    TFTF_BUILD:
      type: string
      options:
        - release
        - debug
      value: release
    TFTF_LOG_LEVEL:
      type: string
      value: 40
    TFTF_SUITE:
      type: string
      value: standard
