# Copyright (c) 2023, Arm Limited.
# SPDX-License-Identifier: MIT

%YAML 1.2
---
description: >-
  The Trusted Firmware-A Tests (TF-A-Tests) is a suite of baremetal tests that
  exercise the Trusted Firmware-A (TF-A) features. This provides a baseline
  configuration that can be customized by higher layers.

build:
  tftf:
    repo:
      remote: https://git.trustedfirmware.org/TF-A/tf-a-tests.git
      revision: v2.14.0

    toolchain: aarch64-none-elf-

    params:
      PLAT: fvp
      DEBUG: 0
      ENABLE_REALM_PAYLOAD_TESTS: 1

    build:
      # tfa-tests has makefile dependency bug that makes parallel make for more
      # than ~8 jobs unreliable, so limit it to 8.
      - "make BUILD_BASE=${param:builddir} ${param:join_equal} -j$$(( ${param:jobs} < 8 ? ${param:jobs} : 8 )) all"

    artifacts:
      TFTF_BIN: ${param:builddir}/fvp/release/tftf.bin
      SP_LAYOUT: ${param:builddir}/fvp/release/sp_layout.json

